### ISSUE TITLE
How to activate the mega menu?

### ISSUE THREAD

**Issue by justiny** [SimonPadbury/WBST#1]
Great work.  I'm interested in understanding how you get the mega menu to activate?  Do you have any documentation or direction on that?  Thanks!

**Comment by SimonPadbury** [comment]
Hi Justiny,

Thanks for your interest in WBST. I have modified the code for the mega menu to make it work again (I had made some other changes but didn't notice that I broke meganav). It's working OK now. With this fix I bumped up the version number to 1.4.2 -- you will need to download this latest version.

I also wrote a how-to for meganav in the readme.md
