### ISSUE TITLE
woocommerce.php

### ISSUE THREAD

**Issue by vagu71** [SimonPadbury/WBST#4]
Hi Simon, 

In case the archive-product.php file is to be updated without using hooks, it doesn't work unless this code is added to the woocommerce.php file: 

<?php //woocommerce_content();
                if ( is_single( 'product' ) )
                    {
                        woocommerce_content();
                    }
                else
                    {
                        //For ANY product archive.
                        //Product taxonomy, product search or /shop landing
                        woocommerce_get_template( 'archive-product.php' );
                    }
            ?>

Adding this makes the archive-product.php file come into action. However, this file comes preloaded with 2 functions: 
do_action( 'woocommerce_before_main_content' )
do_action( 'woocommerce_after_main_content' )
(Commenting out these 2 lines in archive-product.php makes the warning go away)
These throw a warning:
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'bst_plus_wrapper_start' not found or invalid function name in /home/devbearand/public_html/hatch/wp-includes/plugin.php on line 503

Any ideas why this could be happening?

Thanks much in advance for looking into this. 

Kind regards,
Varun

**Comment by SimonPadbury** [comment]
Hi Varun,

My mistake, thankyou for finding it :-)

[I have two themes with WooCommerce: WBST and BST-Plus. I had copied the BST-Plus `functions/woocommerce-setup.php` into WBST, but I had not done **search/replace** to change all namespace references `bst_plus_...` to become `wbst_`. So I had not seen some places where I forgot to make this change.]

I have now fixed this problem. 

Please download / or clone again. (Or swap my new `functions/woocommerce-setup.php` for the old one that you have got already.)

Let me know if this still gives a problem for you.

Kind regards,

Varun

**Comment by vagu71** [comment]
Hi Simon, 

Thanks for making the change. It now comes up with the error as below: 

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'wbst_wrapper_start' not found or invalid function name in /home/devbearand/public_html/hatch/wp-includes/plugin.php on line 503

I'm thinking, there's no wbst_wrapper_start function in the file. However there is one reinnervate_wrapper_start() in the same file. Does this also need to be changed to wbst_wrapper_start()?

**Comment by vagu71** [comment]
Making this change comes with the error of not being able to find the definition of the function of_get_option. As this is inside the wbst_wrapper_start() funciton which now runs as its name was changed from reinnervate_wrapper_start() to wbst_wrapper_start()

**Comment by SimonPadbury** [comment]
Thanks vagu71. That was another thing I forgot to change when copying this file from an old project.

I just changed this in WBST.
