### ISSUE TITLE
Custom WooCommerce Taxonomy Pages

### ISSUE THREAD

**Issue by reececropley** [SimonPadbury/WBST#7]
I am not sure if this is the right place to post about my issue. Everything I've searched on-line hasn't helped so far.

I am using your theme alongside a multi-vendor plugin. The vendor page on the plugin uses the taxonomy yith_shop_vendor. I wanted to edit this taxonomy page so I created a taxonomy-yith_shop_vendor.php file to go to inside my /woocommerce folder on the site. 

I then alter the template but no change reflect when I check in the browser.

Can you confirm that this is the correct place to be able to edit the taxonomy page? 

Thanks in advance.

**Comment by SimonPadbury** [comment]
Sorry, I don't know.
