### ISSUE TITLE
Multilevel navbar.

### ISSUE THREAD

**Issue by saqwild** [SimonPadbury/WBST#9]
Hi,
I know I can remove the mega menu, but can I have multi level navbar (upto three level?)

thanks

**Comment by SimonPadbury** [comment]
Hello Saqwild,

Bootstrap doesn't allow grandchild menus. But I found this YouTube tutorial that may help you.

https://www.youtube.com/watch?v=voJSJJrPHEQ

I haven't watched it all yet, but it looks like what you need (except that the tutor is using Drupal, not WordPress)

Kind regards 

Simon
